publish: Fix buid is failing (#656)
* publish: Fix missing xvfb-run

* publish: Install flat-manager-client

Fixes the following error in the deploy step of the publish action:

    Error: Failed to publish the build: Error: Unable to locate executable file: flat-manager-client.
    Please verify either the file path exists or the file can be found within a directory specified
    by the PATH environment variable. Also check the file mode to verify the file is executable.

* Add verify